# Generated by Django 5.1 on 2024-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("position", models.CharField(max_length=50)),
            ],
        ),
    ]
