# Generated by Django 5.0.7 on 2024-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personal",
            options={"verbose_name": "personal list"},
        ),
        migrations.AlterField(
            model_name="personal",
            name="firstname",
            field=models.CharField(max_length=100, verbose_name="firstname"),
        ),
    ]
